[package]
name = "nng-lab"
version = "0.1.0"
authors = ["yangzifeng <yangzifeng@cetccloud.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nng = "1.0.0"
